import type { Metadata } from "next";
import { Geist, Geist_Mono, Pacifico, Josefin_Sans, Courgette } from "next/font/google";
import "./globals.css";
import Header from "./_components/layout/Header";
import Footer from "./_components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const pacifico = Pacifico({
  weight: "400",
  variable: "--font-pacifico",
  subsets: ["latin"],
})

const josefinSans = Josefin_Sans({
  weight: "400",
  variable: "--font-josephine",
  subsets: ['latin']
})

const courgette = Courgette({
  weight: "400",
  variable: "--font-courgette",
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} ${josefinSans.variable} ${courgette.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-200">
      <Header />
      {children}
      <Footer />
      </body>
    </html>
  );
}
